package tud.iir.web;

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import tud.iir.web.resources.Source;


/**
 * The knowledge unit aggregated result.
 * 
 * The AggregatedResults generated by the SourceAggregator contain references to the WebResults they result from, as well as an aggregated rank value. They are
 * not stored in the database directly, but keep a reference to the Source to which they refer.
 * 
 * @author Christopher Friedrich
 */
public class AggregatedResult implements Serializable {

    private static final long serialVersionUID = -2708748322787381119L;

    private List<WebResult> webresults;
    private float aggregatedRank;
    private Source source;

    public AggregatedResult(List<WebResult> webresults, float aggregatedRank) {
        super();

        this.aggregatedRank = aggregatedRank;
        this.webresults = webresults;

        if (webresults != null && webresults.size() > 0) {
            this.source = new Source(webresults.get(0).getUrl());
        } else {
            this.source = null;
        }
    }

    public List<WebResult> getWebresults() {
        return webresults;
    }

    public float getAggregatedRank() {
        return aggregatedRank;
    }

    public Source getSource() {
        return source;
    }

    public Set<Integer> getSearchEngines() {
        HashSet<Integer> searchengines = new HashSet<Integer>();
        if (webresults != null && webresults.size() > 0) {
            for (WebResult wr : webresults) {
                searchengines.add(wr.getIndex());
            }
        }
        return searchengines;
    }
}
