package ws.palladian.semantics;

public enum EnglishTense {
    SIMPLE_PRESENT, PRESENT_PROGRESSIVE, SIMPLE_PAST, PAST_PROGRESSIVE, PRESENT_PERFECT, PRESENT_PERFECT_PROGRESSIVE, PAST_PERFECT, PAST_PERFECT_PROGRESSIVE, WILL_FUTURE, GOING_TO_FUTURE, FUTURE_PROGRESSIVE, FUTURE_PERFECT, FUTURE_PERFECT_PROGRESSIVE
}
