package ws.palladian.web.wiki.data;

import java.util.Date;

/**
 * Represents a simplified revision of a Wiki page.
 * 
 * @author Sandro Reichert
 * 
 */
public class Revision {

    /**
     * The page's revision id, generated by Wiki.
     */
    private final long revisionID;

    /**
     * The timestamp this revision has been created on the Wiki.
     */
    private final Date timestamp;

    /**
     * The name of the Wiki user that created this revision.
     */
    private final String user;

    /**
     * A revision as retrieved from the Wiki
     * 
     * @param revisionID The page's revision id, generated by Wiki.
     * @param timestamp The timestamp this revision has been created on the Wiki.
     * @param user The name of the Wiki user that created this revision.
     */
    public Revision(final long revisionID, final Date timestamp, final String user) {
        this.revisionID = revisionID;
        this.timestamp = timestamp;
        this.user = user;
    }

    /**
     * @return The page's revision id, generated by Wiki.
     */
    public final long getRevisionID() {
        return revisionID;
    }

    /**
     * @return The timestamp this revision has been created on the Wiki.
     */
    public final Date getTimestamp() {
        return timestamp;
    }

    /**
     * @return The name of the Wiki user that created this revision.
     */
    public final String getAuthor() {
        return user;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (revisionID ^ (revisionID >>> 32));
        result = prime * result + ((timestamp == null) ? 0 : timestamp.hashCode());
        result = prime * result + ((user == null) ? 0 : user.hashCode());
        return result;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Revision other = (Revision) obj;
        if (revisionID != other.revisionID)
            return false;
        if (timestamp == null) {
            if (other.timestamp != null)
                return false;
        } else if (!timestamp.equals(other.timestamp))
            return false;
        if (user == null) {
            if (other.user != null)
                return false;
        } else if (!user.equals(other.user))
            return false;
        return true;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Revision [revisionID=" + revisionID + ", timestamp=" + timestamp + ", user=" + user + "]";
    }

}
